force-app/main/default/objects/NHS_Property__c/NHS_Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Agent_1__c.field-meta.xml
<CustomField>
    <fullName>Agent_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Agent 1)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_1_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_1_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_1_Logo__c.field-meta.xml
<CustomField>
    <fullName>Agent_1_Logo__c</fullName>
    <label>Agent 1 Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_1_Valuation_Requested_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_1_Valuation_Requested_Date_Time__c</fullName>
    <label>Valuation Requested Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_2__c.field-meta.xml
<CustomField>
    <fullName>Agent_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Estate Agents</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Agent 2)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_2_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_2_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_2_Valuation_Requested_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_2_Valuation_Requested_Date_Time__c</fullName>
    <label>Valuation Requested Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_3__c.field-meta.xml
<CustomField>
    <fullName>Agent_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent 3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Agent 3)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_3_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_3_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_3_Valuation_Requested_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_3_Valuation_Requested_Date_Time__c</fullName>
    <label>Valuation Requested Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Applicant)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Reference_Number__c</fullName>
    <displayFormat>ARN2014{00000}</displayFormat>
    <label>Application Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>NHS_Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/accountController.cls
public without sharing class accountController {
    
    @AuraEnabled(cacheable=true)
    public static Account getData(string recId){
        system.debug(recId);
        return[select id, name, Email__c, phone, Agent_1_Logo__c, Logo_URL__c from account where id =: recId limit 1];
    }

    @AuraEnabled(cacheable=true)
    public static String getAccountFileUrl(Id accountId) {
        Account acc = [SELECT Id,  Logo_URL__c FROM Account WHERE Id = :accountId LIMIT 1];
        string url = acc.Logo_URL__c;
        return url;
        //	return 'https://nhsolutions--training.sandbox.file.force.com/sfc/dist/version/renditionDownload?rendition=ORIGINAL_Jpeg&versionId=068KG000000MOI6&operationContext=DELIVERY&contentId=05TKG000000BjL6&page=0&d=/a/KG000000CfeD/gFQt0b_5Pn5HApk4ly5bkWYGUosqrPKwsnquBWuqbhI&oid=00D7a0000005DDN&dpt=null&viewId=';
    }


    @AuraEnabled(cacheable=true)
    public static Opportunity getOppData(string recsId, string acId){
        system.debug(recsId);
         system.debug(acId);
        Opportunity op = [select id,Agent_1__c, Agent_2__c, Agent_3__c, Applicant__c, Application_Reference_Number__c,
        Agent_1_Appointment__c, Agent_2_Appointment__c, Agent_3_Appointment__c,
                          Applicant__r.Name, Applicant__r.Email, Property__r.Name, Name, Applicant__r.Phone,Agent_1_Valuation_Requested_Date_Time__c,
                          Agent_2_Valuation_Requested_Date_Time__c,Agent_3_Valuation_Requested_Date_Time__c
                          from Opportunity where Id =:recsId AND (Agent_1__c =:acId OR Agent_2__c  =:acId OR Agent_3__c  =:acId) limit 1];
       
        return op;
    }
    
       @AuraEnabled(cacheable=true)
    public static Boolean isHouseBuilderRecordType(Id accountId) {
        system.debug('accountId-'+ accountId);
        String houseBuilderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('House Builder').getRecordTypeId();
        Account acc = [SELECT RecordTypeId FROM Account WHERE Id =:accountId LIMIT 1];
        boolean flag = (acc.RecordTypeId == houseBuilderRecordTypeId);
        system.debug('flag-'+ flag);
        return flag;
    }
 

    @AuraEnabled
    public static map <string, string> createForm(Valuation_Assessment__c jsonDatalist){
         system.debug('dataList : '+jsonDatalist);
        map<string, string> resMap = new map<string, string>();
         try{
      
        insert jsonDatalist;
             resMap.put('success', jsonDatalist.Id);
        return resMap;
         }catch (Exception e) {
            System.debug('Error in lightning picklist values : '+e.getMessage()+' at line no :'+e.getLineNumber());
            // return null;
            resMap.put('fail', e.getMessage());
             return resMap;
        }
    }
    
    
}