force-app/main/default/objects/NHS_Property__c/NHS_Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Agent_1__c.field-meta.xml
<CustomField>
    <fullName>Agent_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Agent 1)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Expectations__c.field-meta.xml
<CustomField>
    <fullName>Client_Expectations__c</fullName>
    <label>Client Expectations</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_of_Application_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Application_Received__c</fullName>
    <label>Date of Application Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Development__c.field-meta.xml
<CustomField>
    <fullName>Development__c</fullName>
    <label>Development</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ETA_Comp_End__c.field-meta.xml
<CustomField>
    <fullName>ETA_Comp_End__c</fullName>
    <label>ETA Comp - End</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ETA_Comp_Start__c.field-meta.xml
<CustomField>
    <fullName>ETA_Comp_Start__c</fullName>
    <label>ETA Comp - Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/House_Builder__c.field-meta.xml
<CustomField>
    <fullName>House_Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Builder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NHS_Process__c.field-meta.xml
<CustomField>
    <fullName>NHS_Process__c</fullName>
    <label>NHS Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Vendor Availability</fullName>
            </value>
            <value>
                <fullName>Agents Booked</fullName>
            </value>
            <value>
                <fullName>Figures to chased</fullName>
                <label>Figures to chase</label>
            </value>
            <value>
                <fullName>Figures returned</fullName>
            </value>
            <value>
                <fullName>Valuations Ready</fullName>
            </value>
            <value>
                <fullName>Final Checks</fullName>
            </value>
            <value>
                <fullName>Vendor Discussions</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NHS_Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>NHS_Sales_Advisor__c</fullName>
    <label>NHS Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jordan Edmondson</fullName>
            </value>
            <value>
                <fullName>Natasha Turner</fullName>
            </value>
            <value>
                <fullName>Ruth O’Connell</fullName>
            </value>
            <value>
                <fullName>Amy Jackson</fullName>
            </value>
            <value>
                <fullName>Sarah Binns</fullName>
            </value>
            <value>
                <fullName>Charlotte Horwell</fullName>
            </value>
            <value>
                <fullName>Gina Brookes</fullName>
            </value>
            <value>
                <fullName>Akash G</fullName>
                <isActive>false</isActive>
                <label>Akash G</label>
            </value>
            <value>
                <fullName>Deepak R</fullName>
                <isActive>false</isActive>
                <label>Deepak R</label>
            </value>
            <value>
                <fullName>Gokul S</fullName>
                <isActive>false</isActive>
                <label>Gokul S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <label>Plot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>NHS_Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scheme</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_House__c.field-meta.xml
<CustomField>
    <fullName>Type_of_House__c</fullName>
    <label>Type of House</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bunglow</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_1__c.field-meta.xml
<CustomField>
    <fullName>Vendor_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Vendor 1)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_2__c.field-meta.xml
<CustomField>
    <fullName>Vendor_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Scheme.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New Home</fullName>
    </customValue>
    <customValue>
        <fullName>Part Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Sale</fullName>
    </customValue>
    <customValue>
        <fullName>PX or AS</fullName>
    </customValue>
    <customValue>
        <fullName>Home Change</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Move</fullName>
    </customValue>
    <customValue>
        <fullName>Move Assist</fullName>
    </customValue>
    <customValue>
        <fullName>Smooth Move</fullName>
    </customValue>
    <customValue>
        <fullName>Easy Move</fullName>
    </customValue>
    <customValue>
        <fullName>Movemaker</fullName>
    </customValue>
    <masterLabel>Scheme</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApplicationFormController.cls
public class ApplicationFormController {

    @AuraEnabled
    public static Map<String, String> saveApplication(Map<String, Object> jsonData, String recordtype) {
        System.debug('jsonData' + ' ----' + JSON.serialize(jsonData));
        Map<String, String> returnMap = new Map<String, String>();
        List<String> ConIdlist = new List<String>();
        String recType = 'Part Exchange - Applications';
        String ids = '';

        Savepoint sp;
        
        try {
            // Set savepoint to rollback changes if needed
            sp = Database.setSavepoint();
            
            New_Home_Solution__mdt config = New_Home_Solution__mdt.getInstance('NHS');
            Account ac = [SELECT Id FROM Account WHERE Name = :config.Name__c AND Phone = :config.Phone__c LIMIT 1];
            
            NHS_Property__c prop = new NHS_Property__c();
            Contact vendor1 = new Contact();
            Contact vendor2 = new Contact();
            
            // Determine record type
            if (String.valueOf(recordtype) == 'New Home') {
                recType = 'New Home Sales';
            } else if (String.valueOf(recordtype) == 'Part Exchange') {
                recType = 'Part Exchange - Applications';
            } else if (String.valueOf(recordtype) == 'Assisted Sale') {
                recType = 'Assisted Sales';
            }
            
            Id partExchange = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(recType).getRecordTypeId();
            Id houseBuilder = Schema.SObjectType.Account.getRecordTypeInfosByName().get('House Builder').getRecordTypeId();
            
            // Insert vendor1
            vendor1.FirstName = String.valueOf(jsonData.get('firstname'));
            vendor1.LastName = String.valueOf(jsonData.get('lastname'));
            vendor1.Email = String.valueOf(jsonData.get('email'));
            vendor1.MobilePhone = String.valueOf(jsonData.get('mobilePhone'));
            insert vendor1;
            
            if (vendor1 != null) {
                Account houseBuilderAccount = new Account();
                houseBuilderAccount.Name = vendor1.LastName + ' Household';
                houseBuilderAccount.Phone = vendor1.MobilePhone;
                houseBuilderAccount.Email__c = vendor1.Email;
                houseBuilderAccount.RecordTypeId = houseBuilder;
                insert houseBuilderAccount;
                
                if (houseBuilderAccount != null) {
                    vendor1.AccountId = houseBuilderAccount.Id;
                    update vendor1;
                }
            }

            if (String.valueOf(jsonData.get('lastname1')) != null && String.valueOf(jsonData.get('lastname1')) != '') {
                vendor2.FirstName = String.valueOf(jsonData.get('firstname1'));
                vendor2.LastName = String.valueOf(jsonData.get('lastname1'));
                vendor2.Email = String.valueOf(jsonData.get('email1'));
                vendor2.MobilePhone = String.valueOf(jsonData.get('mobilePhone1'));
                
                if (vendor2.LastName != null) {
                    insert vendor2;
                    ConIdlist.add(vendor2.Id);
                }
            }
            
            ConIdlist.add(vendor1.Id);
            
            // Populate and insert property record
            prop.Address__Street__s = String.valueOf(jsonData.get('street'));
            prop.Address__City__s = String.valueOf(jsonData.get('city'));
            prop.Address__PostalCode__s = String.valueOf(jsonData.get('pcode'));
            prop.Name = prop.Address__Street__s + ' ' + prop.Address__City__s + ' ' + prop.Address__PostalCode__s;
            
            insert prop;
            ids = prop.Id;

            // Populate opportunity
            Opportunity opp = new Opportunity();
            if (prop.Name != '') {
                opp.Name = prop.Name;
                opp.Application_Name__c = opp.Name;
                opp.Property__c = ids;
            }
            
            if (String.valueOf(jsonData.get('expectation')) != '') {
                opp.Client_Expectations__c = Integer.valueOf(jsonData.get('expectation'));
            }
            if (String.valueOf(jsonData.get('type')) != '') {
                opp.Type_of_House__c = String.valueOf(jsonData.get('type'));
            }
            if (String.valueOf(jsonData.get('scheme')) != '') {
                opp.Scheme__c = String.valueOf(jsonData.get('scheme'));
            }
            if (String.valueOf(jsonData.get('startDate')) != '') {
                opp.ETA_Comp_Start__c = String.valueOf(jsonData.get('startDate'));
            }
            if (String.valueOf(jsonData.get('endDate')) != '') {
                opp.ETA_Comp_End__c = String.valueOf(jsonData.get('endDate'));
            }
            if (String.valueOf(jsonData.get('notes')) != '') {
                opp.Notes__c = String.valueOf(jsonData.get('notes'));
            }
            opp.Vendor_1__c = vendor1.Id;
            opp.Vendor_2__c = vendor2.Id != null ? vendor2.Id : null;
            if (ac != null) {
                opp.Agent_1__c = ac.Id;
            }
            if (String.valueOf(jsonData.get('houseBuilder')) != '') {
                opp.House_Builder__c = String.valueOf(jsonData.get('houseBuilder'));
            }
            if (String.valueOf(jsonData.get('development')) != '') {
                opp.Development__c = String.valueOf(jsonData.get('development'));
            }
            if (String.valueOf(jsonData.get('plot')) != '') {
                opp.Plot__c = String.valueOf(jsonData.get('plot'));
            }
            if (String.valueOf(jsonData.get('applicationRecDate')) != '') {
                opp.Date_of_Application_Received__c = Date.valueOf(String.valueOf(jsonData.get('applicationRecDate')));
            }
            opp.RecordTypeId = partExchange;
              if(string.valueOf(jsonData.get('salesAdvisor')) !=''){
                opp.NHS_Sales_Advisor__c = string.valueOf(jsonData.get('salesAdvisor'));
            }
            opp.CloseDate = System.today();
            opp.StageName = 'To be contacted';
            opp.AccountId = vendor1.AccountId;
            opp.NHS_Process__c = 'Application';

            insert opp;

            if (opp.Id != null) {
                returnMap.put('y', opp.Id);
            }

            return returnMap;

        } catch (Exception e) {
            Database.rollback(sp);
            returnMap.put('n', 'Error');
            System.debug('ERROR=====' + e.getMessage() + '  ' + e.getLineNumber());
            return returnMap;
        }
    }
}