force-app/main/default/objects/Opportunity/fields/Agent_1_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_1_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_2_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_2_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_3_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Agent_3_Appointment__c</fullName>
    <label>Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NHS_Process__c.field-meta.xml
<CustomField>
    <fullName>NHS_Process__c</fullName>
    <label>NHS Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Vendor Availability</fullName>
            </value>
            <value>
                <fullName>Agents Booked</fullName>
            </value>
            <value>
                <fullName>Figures to chased</fullName>
                <label>Figures to chase</label>
            </value>
            <value>
                <fullName>Figures returned</fullName>
            </value>
            <value>
                <fullName>Valuations Ready</fullName>
            </value>
            <value>
                <fullName>Final Checks</fullName>
            </value>
            <value>
                <fullName>Vendor Discussions</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityStageUpdaterBatchTest.cls
@isTest
public class OpportunityStageUpdaterBatchTest {
    @isTest
    public static void testTheMethod(){
        //creat a updated list 
        List<Opportunity> oppListToUpdated = new List<Opportunity>();
        for(Integer i=0; i<200; i++){
            Opportunity newOpp = new Opportunity();
            newOpp.Name = 'test opportunity';
            newOpp.CloseDate = Date.today().addDays(3);
            newOpp.Application_Name__c = 'test application';
            newOpp.StageName = 'New Appplication';
            newOpp.NHS_Process__c = 'Agents Booked';
            newOpp.Agent_1_Appointment__c = Date.today();
            newOpp.Agent_2_Appointment__c = Date.today().addDays(1);
            newOpp.Agent_3_Appointment__c = Date.today().addDays(2);
            oppListToUpdated.add(newOpp);
        }
        insert oppListToUpdated;
                
        
        Test.startTest();
        OpportunityStageUpdaterBatch osb = new OpportunityStageUpdaterBatch();
        Database.executeBatch(osb);
        OpportunityStageUpdaterSchedule osbs = new OpportunityStageUpdaterSchedule();
        System.schedule('Test Schedule' ,'0 5 * * * ?',osbs);
        Test.stopTest();
    }
}