force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Applicant)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Archived_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Archived_Approval_Status__c</fullName>
    <label>UnArchived Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/House_Builder__c.field-meta.xml
<CustomField>
    <fullName>House_Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Builder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Sales_Advisor__c</fullName>
    <label>Sales Advisor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ArchivedApplicationKanbanController.cls
/**
* @File Name : ArchivedApplicationKanbanController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : March 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 21, 2025 |   | Initial Version
**/

public class ArchivedApplicationKanbanController {
    @AuraEnabled(cacheable=true)
     public static Map<String, Object> getOpportunities(Integer limitSize, Integer offsetValue) {
       // List<Map<String, Object>> finalMapList = new List<Map<String, Object>>();
        Map<String, Object> opportunityMap = new Map<String, Object>();

        // Fetching opportunities
        List<Opportunity> finalList = [
            SELECT Id, Name, Sales_Advisor__c, StageName ,House_Builder__c,  House_Builder__r.Name, Archived_Approval_Status__c, Applicant__r.Name, Applicant__c
            FROM Opportunity 
            WHERE Archived__c = true  ORDER BY CreatedDate DESC 
            LIMIT :limitSize OFFSET :offsetValue
        ];

        Integer totalCount = [SELECT COUNT() FROM Opportunity];

        opportunityMap.put('opportunities', finalList);
        opportunityMap.put('totalCount', totalCount);


        return opportunityMap;
    }

}