force-app/main/default/objects/Opportunity/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Reference_Number__c</fullName>
    <displayFormat>ARN2014{00000}</displayFormat>
    <label>Application Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Development__c.field-meta.xml
<CustomField>
    <fullName>Development__c</fullName>
    <label>Development</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/House_Builder__c.field-meta.xml
<CustomField>
    <fullName>House_Builder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Builder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NHS_Process__c.field-meta.xml
<CustomField>
    <fullName>NHS_Process__c</fullName>
    <label>NHS Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Vendor Availability</fullName>
            </value>
            <value>
                <fullName>Agents Booked</fullName>
            </value>
            <value>
                <fullName>Figures to chased</fullName>
                <label>Figures to chase</label>
            </value>
            <value>
                <fullName>Figures returned</fullName>
            </value>
            <value>
                <fullName>Valuations Ready</fullName>
            </value>
            <value>
                <fullName>Final Checks</fullName>
            </value>
            <value>
                <fullName>Vendor Discussions</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NHS_Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>NHS_Sales_Advisor__c</fullName>
    <label>NHS Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jordan Edmondson</fullName>
            </value>
            <value>
                <fullName>Natasha Turner</fullName>
            </value>
            <value>
                <fullName>Ruth O’Connell</fullName>
            </value>
            <value>
                <fullName>Amy Jackson</fullName>
            </value>
            <value>
                <fullName>Sarah Binns</fullName>
            </value>
            <value>
                <fullName>Charlotte Horwell</fullName>
            </value>
            <value>
                <fullName>Gina Brookes</fullName>
            </value>
            <value>
                <fullName>Akash G</fullName>
                <isActive>false</isActive>
                <label>Akash G</label>
            </value>
            <value>
                <fullName>Deepak R</fullName>
                <isActive>false</isActive>
                <label>Deepak R</label>
            </value>
            <value>
                <fullName>Gokul S</fullName>
                <isActive>false</isActive>
                <label>Gokul S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <label>Plot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Sales_Advisor__c</fullName>
    <label>Sales Advisor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AllApplicationKanbanTest.cls
@isTest
public class AllApplicationKanbanTest {
    @testSetup
    static void testSetupData(){
        //create the user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com.' + System.currentTimeMillis(),
            ProfileId = p.Id,
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
            insert testUser;
            
            
           //create the Account (House Builder);
        Account houseBuilder = new Account();
        houseBuilder.Name = 'Test HouseBuilder';
        houseBuilder.BillingCity = 'Test City';
        insert houseBuilder;
        
        
        //create the application
        Opportunity application = new Opportunity();
        application.Name = 'Test app application';
        application.StageName = 'New Application';
        application.Application_Name__c = 'Test application';
        application.House_Builder__c = houseBuilder.Id;
        application.NHS_Sales_Advisor__c ='Gina Brookes';
        application.Plot__c = 'Test Plot';
        application.Development__c = 'Test Development';
       // application.Application_Reference_Number__c = ''
        application.CloseDate = Date.today();
        application.OwnerId = testUser.Id;
        insert application;
    }
    
    @isTest
    static void testGetOpportunityStage(){
       Opportunity opp = [SELECT Id, Name, StageName, NHS_Process__c, House_Builder__r.Name, Sales_Advisor__c,
                           Owner.Name, NHS_Sales_Advisor__c, Application_Reference_Number__c, 
                           Plot__c, House_Builder__r.BillingCity, CreatedDate 
                           FROM Opportunity LIMIT 1];
        Test.startTest();
      //  new AllApplicationKanban.OpportunityWrapper(opp[0]);
      string name = 'Test app application';
      string stage = 'New Application';
        List<AllApplicationKanban.OpportunityStageWrapper> oppStages = AllApplicationKanban.getOpportunityStages(name, stage, false);
        AllApplicationKanban.OpportunityWrapper wrapper = new AllApplicationKanban.OpportunityWrapper(opp);
        AllApplicationKanban.fetchOpportunitiesByStage(stage, 20);
        Test.stopTest();
    }
      
}